MAX_PITCH_DISTANCE = 65
MAX_BEAT_DUR_DISTANCE = 22
MAX_BEAT_ONSET_DISTANCE = 15
MAX_BEAT_ONSET_OFFSET = 10
MAX_ONSET_DISTANCE = 30
MAX_INDEX_DISTANCE = 30
MAX_LENGTH_DISTANCE = 30
MAX_DEGREE_DISTANCE = 7
