import voicesep.utils.constants as const

def create(voice):
  return [
    # Pitch
    *(
      lower <= voice.pitch_space and voice.pitch_space < upper
      for lower, upper in range(40, 80)
    )

    *(
      lower <= voice.avg_pitch_space and voice.avg_pitch_space < upper
      for lower, upper in range(40, 80)
    )

      # Voice above
    abs(voice.note.pitch_space - voice.voice_above.pitch_space) / const.MAX_PITCH_DISTANCE if voice.voice_above else 1,
    abs(voice.note.pitch_space - voice.voice_below.pitch_space) / const.MAX_PITCH_DISTANCE if voice.voice_below else 1,

    voice.blocked,

    # Div note distance
    # 1 if len(voice.pairs.rightvoice.min_pitch_space < 40,
    voice.div_count == 0,
    voice.div_count == 1,
    voice.div_count == 2,
    voice.div_count == 3,

    # Temporal
    voice.note.beat_duration >= 4,
    voice.note.beat_duration >= 3 and voice.note.beat_duration < 4,
    voice.note.beat_duration >= 2 and voice.note.beat_duration < 3,
    voice.note.beat_duration >= 1.75 and voice.note.beat_duration < 2,
    voice.note.beat_duration >= 1.5 and voice.note.beat_duration < 1.75,
    voice.note.beat_duration >= 1.25 and voice.note.beat_duration < 1.5,
    voice.note.beat_duration >= 1 and voice.note.beat_duration < 1.25,
    voice.note.beat_duration >= 0.875 and voice.note.beat_duration < 1,
    voice.note.beat_duration >= 0.75 and voice.note.beat_duration < 0.875,
    voice.note.beat_duration >= 0.625 and voice.note.beat_duration < 0.75,
    voice.note.beat_duration >= 0.5 and voice.note.beat_duration < 0.625,
    voice.note.beat_duration >= 0.375 and voice.note.beat_duration < 0.5,
    voice.note.beat_duration >= 0.25 and voice.note.beat_duration < 0.375,
    voice.note.beat_duration >= 0.125 and voice.note.beat_duration < 0.25,
    voice.note.beat_duration < 0.125,

    voice.rest_count_top == 0,
    voice.rest_count_top == 1,
    voice.rest_count_top == 2,
    voice.rest_count_top == 3,
    voice.rest_count_top == 4,
    voice.rest_count_top == 5,
    voice.rest_count_top > 5,

    voice.rest_count_bottom == 0,
    voice.rest_count_bottom == 1,
    voice.rest_count_bottom == 2,
    voice.rest_count_bottom == 3,
    voice.rest_count_bottom == 4,
    voice.rest_count_bottom == 5,
    voice.rest_count_bottom > 5,

    voice.dur_diff_count_above == 0,
    voice.dur_diff_count_above == 1,
    voice.dur_diff_count_above == 2,
    voice.dur_diff_count_above == 3,
    voice.dur_diff_count_above == 4,
    voice.dur_diff_count_above == 5,
    voice.dur_diff_count_above > 5,

    voice.dur_diff_count_below == 0,
    voice.dur_diff_count_below == 1,
    voice.dur_diff_count_below == 2,
    voice.dur_diff_count_below == 3,
    voice.dur_diff_count_below == 4,
    voice.dur_diff_count_below == 5,
    voice.dur_diff_count_below > 5,

   
    # Positional
    voice.note.index == 0,
    voice.note.index == 1,
    voice.note.index == 2,
    voice.note.index == 3,
    voice.note.index == 4,
    voice.note.index == 5,
    voice.note.index == 6,
    voice.note.index == 7,

    voice.subset_index == 0,
    voice.subset_index == 1,
    voice.subset_index == 2,
    voice.subset_index == 3,
    voice.subset_index == 4,
    voice.subset_index == 5,
    voice.subset_index == 6,
    voice.subset_index == 7,
    voice.subset_index == 8,
    voice.subset_index == 9,
    voice.subset_index == 10,
    voice.subset_index == 11,
    voice.subset_index == 12,
    voice.subset_index == 13,
    voice.subset_index == 14,

    voice.last_index == 0,
    voice.last_index == 0.5,
    voice.last_index == 1,
    voice.last_index == 1.5,
    voice.last_index == 2,
    voice.last_index == 2.5,
    voice.last_index == 3,
    voice.last_index == 3.5,
    voice.last_index == 4,
    voice.last_index == 4.5,
    voice.last_index == 5,
    voice.last_index == 5.5,
    voice.last_index == 6,
    voice.last_index == 6.5,
    voice.last_index == 7,
    voice.last_index == 7.5,
    voice.last_index == 8,
    voice.last_index == 8.5,
    voice.last_index == 9,
    voice.last_index == 9.5,
    voice.last_index == 10,

    voice.note.chord_length == 1,
    voice.note.chord_length == 2,
    voice.note.chord_length == 3,
    voice.note.chord_length == 4,
    voice.note.chord_length == 5,
    voice.note.chord_length == 6,
    voice.note.chord_length == 7,
    voice.note.chord_length == 8,

    voice.subset_length == 1,
    voice.subset_length == 2,
    voice.subset_length == 3,
    voice.subset_length == 4,
    voice.subset_length == 5,
    voice.subset_length == 6,
    voice.subset_length == 7,
    voice.subset_length == 8,
    voice.subset_length == 9,
    voice.subset_length == 10,
    voice.subset_length == 11,
    voice.subset_length == 12,
    voice.subset_length == 13,
    voice.subset_length == 14,
    voice.subset_length == 15,

    voice.last_length == 1,
    voice.last_length == 2,
    voice.last_length == 3,
    voice.last_length == 4,
    voice.last_length == 5,
    voice.last_length == 6,
    voice.last_length == 7,
    voice.last_length == 8,
    voice.last_length == 9,
    voice.last_length == 10,
    voice.last_length == 11,
   
    voice.length_top == 1,
    voice.length_top == 2,
    voice.length_top == 3,
    voice.length_top == 4,
    voice.length_top == 5,
    voice.length_top == 6,
    voice.length_top == 7,
    voice.length_top == 8,
    voice.length_top == 9,
    voice.length_top == 10,
    
    voice.length_bottom == 1,
    voice.length_bottom == 2,
    voice.length_bottom == 3,
    voice.length_bottom == 4,
    voice.length_bottom == 5,
    voice.length_bottom == 6,
    voice.length_bottom == 7,
    voice.length_bottom == 8,
    voice.length_bottom == 9,
    voice.length_bottom == 10,

    voice.position == 0,
    voice.position == 1,
    voice.position == 2,
    voice.position == 3,
    voice.position == 4,
    voice.position == 5,
    voice.position == 6,
    voice.position == 7,
    voice.position == 8,
    voice.position > 8,

    voice.note_count == 1,
    voice.note_count == 2,
    voice.note_count == 3,
    voice.note_count == 4,
    voice.note_count == 5,
    voice.note_count == 6,
    voice.note_count == 7,
    voice.note_count == 8,
    voice.note_count == 9,
    voice.note_count == 10,
    voice.note_count == 11,
    voice.note_count == 12,
  ]
